### ISSUE TITLE
PrintPreview is showing images as it should (black box)

### ISSUE THREAD

**Issue by romerfel** [BerndGabriel/HtmlViewer#326]
I have just upgraded to Delphi Rad Studio 11.2 and installed as well the the HTMLViewer, which I am using since years.  But I am facing now an issue with the PrintPreview, where all images are not displayed correctly (see attached printscreens). 

The HtmlViewer itself shows the image as it should:
![HtmlViewer - OK](https://user-images.githubusercontent.com/19837033/198988375-f439e07c-ff2d-41c6-8d76-3d0cb14a7a6a.png)

But the issue happens in the PrintPreview, where all images are displayed "black"
![PrintPreview - NOK](https://user-images.githubusercontent.com/19837033/198988486-b4b35cc7-f1f7-48b0-9ebe-e3423bc34d5e.png)

The same issue is as well reproducable with the HtmlDemo app, provided with the component source code. 

Would be great if somebody could help me to get this fixed.

**Comment by BerndGabriel** [comment]
In version 11.9 there was a transparency issue with png images. Try the trunk version where it has been fixed.

**Comment by romerfel** [comment]
Hi Bernd 

Thank you very much for your quick feedback.

Do you with the "master" branch with "trunk version"?
![31-10-2022_14-59-51](https://user-images.githubusercontent.com/19837033/199026022-9210b6ab-079a-4dd6-a427-458aa7870fd5.png)

**Comment by BerndGabriel** [comment]
Sorry, yes.

**Comment by romerfel** [comment]
Hi Gabriel

I have downloaded and installed the "master" branch and recompiled my application. The issue still happens:
![01-11-2022_08-31-25](https://user-images.githubusercontent.com/19837033/199182090-e327a325-86e0-4a85-8f65-337f13450860.png)

And could it be, that the print preview is now using a different font? It does not look like as the original report (the font is different).

**Comment by BerndGabriel** [comment]
Can you post or email the used html and image files/text, please?

Using a different font is not intended. Usually the print/preview looks like the "original" in the HtmlViewer.

**Comment by romerfel** [comment]
Hi Gabriel

I got it working as before, by adjusting the following file "htmlcons.inc" and recompiling it. Have "deactivated" the following 2 compliler directives:

- HasGDIPlus
- NoGDIPlus

`
  {$ifdef Compiler22_Plus}
    {.$define HasGDIPlus}
  {$else}
    {$define TSearchRecHasNoTimestamp}
  {$endif}

{.$define NoGDIPlus} {The gdiplus.dll provides Alpha transparency support for
        PNG images and provides support for TIFF images.
        If, for some reason the use of the gdiplus.dll is
        undesirable, define "NoGDIPlus" by removing the '.'.}

`
